# 配置文件
# 插件版本: 1.1.0

# Webhook设置
webhook:
  # Webhook URL列表，可以配置一个或多个URL
  # 例如: 
  # urls: 
  #   - "https://example.com/webhook1"
  #   - "https://example.com/webhook2"
  # 或者单个URL:
  # url: "https://example.com/webhook"
  urls:
    - "https://example.com/webhook"
  # 是否启用Webhook功能 (全局开关)
  enabled: true
  # 连接超时时间（毫秒）
  timeout: 5000
  # 失败重试次数
  retry-count: 3
  # 重试延迟（毫秒）
  retry-delay: 2000

# 事件设置
events:
  # 登录事件
  login:
    # 是否启用此事件的上报
    enabled: true
    # 消息模板，%player%会被替换为玩家名称
    message: "%player% 登录了服务器"
  
  # 离开事件
  quit:
    enabled: true
    message: "%player% 离开了服务器"
  
  # 死亡事件
  death:
    enabled: true
    message: "%player% 死亡了"

  # 聊天事件
  chat:
    enabled: true
    # %player% - 玩家名, %message% - 聊天内容
    message: "%player% 说: %message%"

  # 指令事件
  command:
    enabled: true
    # %player% - 玩家名, %command% - 指令内容
    message: "%player% 执行了指令: %command%"

# 日志设置
logging:
  # 是否启用插件日志
  enabled: true
  # 日志级别：INFO, WARNING, SEVERE (或更详细的 Java Logging Levels)
  level: "INFO"
  # 是否记录成功的webhook调用
  log-success: true
  # 是否记录失败的webhook调用
  log-failure: true

