name: Java CI with Maven and Upload Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step to upload the JAR file as an artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: minecraftwebhook.jar # Name of the artifact
        path: target/*.jar # Path to the generated JAR file(s)
        # Optional: Set retention days (default is 90 days)
        # retention-days: 7
